### ISSUE TITLE
Any sample code or project using this package?

### ISSUE THREAD

**Issue by ridislam** [sumityadav/omnipay-paytm#3]
Hello author, im using omnipay in my codeigntier project, and i need this gateway to be integrated, but do you have any sample controller and view code or project for this repo

**Comment by sumityadav** [comment]
I would suggest not to use the package at its current state. 

1. PayTM have released updates and need additional verification steps that the package has not implemented.
1. I have not had time to update since I created. That's the reason the package is not 1.0 yet.
1. This was built with version 2.x of omnipay and everyone is moving to v3.

If the question is specific to integrating Omnipay with CodeIgnitor then I found the following [videos](https://www.youtube.com/results?search_query=CodeIgniter+Omnipay).
